trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseFlutterVersion@0
    inputs:
      version: 'stable'

  - script: |
      flutter pub get
      flutter build web --release
    displayName: 'Build Flutter Web App'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'build/web'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'webapp'